name: Embold Testing

on:
 push:
  branches: [main]


jobs:
   embold_scan_job:
    runs-on: ubuntu-latest
    name: Embold scan
    steps:
      - run: curl -d 'repoBranchOrTag=main&snapshotLabel=firstLabel' -X POST ${{secrets.EMBOLD_URL}}/api/v1/${{secrets.REPO_UID}}/scan
